jenkins:
  systemMessage: "Jenkins says hello world :)\n\n"
  numExecutors: 3
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: admin
        password: ${adminpw}

jobs:
- script: |
    pipelineJob('hello-pipeline-inline') {
      definition { cps { script("""
        pipeline {
          agent any
          stages {
            stage('Hello, World!') {
              steps {
                sh 'echo "Hello, World!"'
              }
            }
          }
        }
      """) } }
    }
