name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdownlint:
    
    runs-on: ubuntu-latest
    name: A job to lint markdown

    steps:
    - uses: actions/checkout@v2
    - uses: figaw/markdownlint@3049c8af233d1df64b8306d0d5f98baa5028e908
      with:
        parameters: "."
