name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdownlint:
    
    runs-on: ubuntu-latest
    name: A job to lint markdown

    steps:
    - uses: figaw/markdownlint@e08f6411b1bfc9fa6de220e5c649ab3c8b473c35
      id: mdl
      with:
        parameters: "."
    - name: Get the logs
      run: echo "${{ steps.mdl.outputs.log }}"
