name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdownlint:
    
    runs-on: ubuntu-latest
    name: A job to lint markdown

    steps:
    - uses: figaw/markdownlint@6776ed999758337f8f74993d69be26a996452737
      id: mdl
      with:
        parameters: .
    - name: Get the logs
      run: echo "${{ steps.mdl.outputs.log }}"
