name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdownlint:
    
    runs-on: ubuntu-latest
    name: A job to lint markdown

    steps:
    - uses: figaw/markdownlint@4546fe95f5178a3ec57f8840490d864b6efc9e13
      with:
        parameters: .
