name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdownlint:
    
    runs-on: ubuntu-latest
    name: A job to lint markdown

    steps:
    - uses: figaw/markdownlint@3049c8af233d1df64b8306d0d5f98baa5028e908
      id: mdl
      with:
        parameters: "."
    - name: Get the logs
      run: echo "${{ steps.mdl.outputs.log }}"
