name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdownlint:
    
    runs-on: ubuntu-latest
    name: A job to lint markdown

    steps:
    - uses: actions/checkout@v2
    - uses: figaw/markdownlint@v1
      with:
        parameters: "."
